name: vtable
description: >-
  A Flutter table widget featuring virtualization, sorting, and custom cell
  rendering.
version: 0.3.1
repository: https://github.com/devoncarew/vtable

topics:
  - widgets

environment:
  sdk: ^3.0.0
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
